apiVersion: v1
kind: Namespace
metadata:
  name: snmp-exporter
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-snmp-exporter
  namespace: flux-system
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-snmp-exporter
  namespace: snmp-exporter
spec:
  interval: 30m
  chart: 
    spec:
      chart: prometheus-snmp-exporter
      version: '>=9.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-snmp-exporter
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Enable host network so the exporter can reach local network devices
    hostNetwork: true
    # Use dnsPolicy: ClusterFirstWithHostNet to maintain DNS resolution
    dnsPolicy: ClusterFirstWithHostNet

