apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../secrets  # Include encrypted secrets
  - metallb-pool.yaml
  - traefik-dashboard.yaml
  - longhorn-dashboard.yaml
  - clusterissuer-staging.yaml
  - clusterissuer-prod.yaml
