---
# Kubernetes native VLAN pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k8s-vlan
  namespace: metallb-system
spec:
  addresses:
    - 10.0.50.200-10.0.50.250
---
# L2 Advertisement
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - k8s-vlan
  # Allow control-plane nodes (ignore exclude-from-external-load-balancers label)
  nodeSelectors:
    - matchLabels:
        kubernetes.io/os: linux
  # Specify physical network interface for Talos nodes
  interfaces:
    - eno1
