apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openwifi-tls
  namespace: openwifi
spec:
  secretName: openwifi-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - openwifi.wilsonfi.dev
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openwifi-prov-tls
  namespace: openwifi
spec:
  secretName: openwifi-prov-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - openwifi-prov.wilsonfi.dev
---
# Gateway UI - main dashboard
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openwifi-gateway-ui
  namespace: openwifi
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openwifi.wilsonfi.dev`)
      kind: Rule
      services:
        - name: owgwui-owgwui
          port: 80
  tls:
    secretName: openwifi-tls-secret
---
# Provisioning UI
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openwifi-prov-ui
  namespace: openwifi
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openwifi-prov.wilsonfi.dev`)
      kind: Rule
      services:
        - name: owprovui-owprovui
          port: 80
  tls:
    secretName: openwifi-prov-tls-secret
