apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-tls
  namespace: pihole
spec:
  secretName: pihole-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - pihole.wilsonfi.dev
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-dashboard
  namespace: pihole
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole.wilsonfi.dev`)
      kind: Rule
      services:
        - name: pihole-web
          port: 80