apiVersion: v1
kind: Namespace
metadata:
  name: ghost
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ghost
  namespace: flux-system
spec:
  type: oci
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  interval: 30m
  chart: 
    spec:
      chart: ghost
      version: '>=6.0.0'
      sourceRef:
        kind: HelmRepository
        name: ghost
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    existingSecret: ghost-login
    service:
      type: ClusterIP
    

