apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capacitor-tls
  namespace: flux-system
spec:
  secretName: capacitor-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - capacitor.wilsonfi.dev
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: capacitor-ui
  namespace: flux-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`capacitor.wilsonfi.dev`)
      kind: Rule
      services:
        - name: capacitor
          port: 9000
  tls:
    secretName: capacitor-tls-secret
