---
# IngressRoute to expose Longhorn dashboard
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: capacitor-ui
  namespace: flux-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`capacitor.wilsonfi.dev`)
      kind: Rule
      services:
        - name: capacitor
          port: 9000
